### PR TITLE
i18n - pulling from tx

### PR DESCRIPTION
**Pull request by ekohl**
@stejskalleos this brings completion to certain languages Satellite cares about. It'd be great to have this released.

### CODE REVIEW

**Comment by stejskalleos** [comment]
@ekohl I see it's still in draft, is it ready for review?

**Comment by stejskalleos** [comment]
Failing rubocop fixed in https://github.com/theforeman/foreman_google/pull/57

**Comment by ekohl** [comment]
I marked it draft since it was incomplete, but the RH translators have finished so I'll update this. For context, you can see that https://www.transifex.com/foreman/foreman/foreman_google/ is now 100% on the languages Satellite is translated into (es, fr, ja, pt_BR, zn_CH).

**Review by stejskalleos — APPROVED** [review]

**Comment by stejskalleos** [comment]
Thanks @ekohl !

**Pull request merged**
