### PR TITLE
GoogleExtensions::AttachedDisk#size_gb

### PR DESCRIPTION
**Pull request by stejskalleos**
Fixing https://github.com/stejskalleos/foreman_google/issues/45

### CODE REVIEW

**Comment by adamruzicka** [comment]
The original issue is gone, but found another one
1) Go to Infrastructure > Compute Resource > $GCE > Compute Profiles > 1-Small (or any really)
2) Change machine type to e2-micro
3) Submit
4) Repeat step 1
5) Try to create a host using the profile from 1)

compute attributes get saved properly between 3 and 4. In step 4 it shows a different machine type (first one that gce's api returns?). In step 5 it does not preselect the saved machine type and again shows a different one

**Comment by stejskalleos** [comment]
@adamruzicka Fixed machine_type, network and external IP (and added tests)

**Review by adamruzicka — APPROVED** [review]
Works well

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
