### PR TITLE
BZ#2166964 - API /:id/available_networks fails with ISE

### PR DESCRIPTION
**Pull request by stejskalleos**
How to test:

```
curl -X GET -k -H 'Content-Type: application/json' -H 'Accept: application/json' -u admin:changeme "https://foreman.example.com/api/compute_resources/:id/available_networks"
```

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
Hey @stejskalleos what was the exact server error, do you recall? just a nil exception?

**Comment by stejskalleos** [comment]
> Hey @stejskalleos what was the exact server error, do you recall? just a nil exception?

```
...

{
  "error": {"message":"Internal Server Error: the server was unable to finish the request. This may be caused by unavailability of some required service, incorrect API call or a server-side bug. There may be more information in the server's logs."}
}
```
`.items` method is not available on the response object

**Review by Ron-Lavi — APPROVED** [review]
Thanks @stejskalleos !

**Comment by Ron-Lavi** [comment]
no merge rights here :P
can you also add the bump commit here?

**Comment by Gauravtalreja1** [comment]
@stejskalleos Thank you for fixing this so quickly. I tested it and it works.

**Pull request merged**
