### PR TITLE
Cleanup code and remove empty folders and .gitkeep files

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by adamruzicka** [comment]
With this I'm unable to provision a new host

```
2022-07-20T10:19:13 [W|app|8fb23f81] »Failed to create a compute gogol (us-central1-a-Google) instance eldon-burress.addie-dulberg.example.com: undefined method `zone' for #<ForemanGoogle::GoogleCompute:0x00007f53a9f4f110>                                                                                                                                                            
 8fb23f81 |  «                                                                                                                                                                               
2022-07-20T10:19:13 [I|app|8fb23f81] Backtrace for '»Failed to create a compute gogol (us-central1-a-Google) instance eldon-burress.addie-dulberg.example.com: undefined method `zone' for #<ForemanGoogle::GoogleCompute:0x00007f53a9f4f110>                                                                                                                                             
 8fb23f81 |  «' error (NoMethodError): undefined method `zone' for #<ForemanGoogle::GoogleCompute:0x00007f53a9f4f110>                                                                                                                                                                                                                                                                     
 8fb23f81 | /home/aruzicka/vcs/foreman/foreman-google/app/lib/google_cloud_compute/compute_attributes.rb:24:in `for_create'                                                                                                                                                                                                                                                               
 8fb23f81 | /home/aruzicka/vcs/foreman/foreman-google/app/models/foreman_google/google_compute.rb:71:in `create_instance'                                                                                                                                                                                                                                                                 
 8fb23f81 | /home/aruzicka/vcs/foreman/foreman-google/app/models/foreman_google/gce.rb:67:in `create_vm'                                                                                                                                                                                                                                                                                  
 8fb23f81 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration/compute.rb:107:in `setCompute'                                                                                                                                                                                                                                                                           
 8fb23f81 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:227:in `execute'                                                                                                                                                                                                                                                                                      
 8fb23f81 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:152:in `block in process'                                                                                                                                                                                                                                                                             
 8fb23f81 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:144:in `each'                                                                                                                                                                                                                                                                                         
 8fb23f81 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:144:in `process'                                                                                                                                                                                                                                                                                      
 8fb23f81 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:44:in `around_save_orchestration'
```

**Comment by stejskalleos** [comment]
@adamruzicka Fixed issue with zone, plus issue with case when Foreman Image have assigned not existing image in the GCE clouds.

And tests.

**Review by adamruzicka — APPROVED** [review]
I have not encountered any issues while playing with this and the changes look reasonable. Let's get this in

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
