### PR TITLE
Destroy VM

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Review by adamruzicka — CHANGES_REQUESTED** [review]
To reproduce
1) Create vm in gce console
2) Import the vm
3) Remove the vm in gce console
4) Try to remove it in foreman

The following error is raised and the host object is not removed

```
2022-05-30T15:42:17 [W|app|f7cb7548] Failed to destroy a compute foreman-google (us-central1-a-Google) instance instance-1: undefined local variable or method `resource_name' for #<ForemanGoogle::GoogleComputeAdapter:0x00007f6059054cc0>                                            
 f7cb7548 | Did you mean?  resource_client                                                                                                                                                                                                                                              
2022-05-30T15:42:17 [I|app|f7cb7548] Backtrace for 'Failed to destroy a compute foreman-google (us-central1-a-Google) instance instance-1: undefined local variable or method `resource_name' for #<ForemanGoogle::GoogleComputeAdapter:0x00007f6059054cc0>                             
 f7cb7548 | Did you mean?  resource_client' error (NameError): undefined local variable or method `resource_name' for #<ForemanGoogle::GoogleComputeAdapter:0x00007f6059054cc0>                                                                                                         
 f7cb7548 | Did you mean?  resource_client                                                                                                                                                                                                                                              
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:131:in `rescue in manage_instance'                                                                                                                                               
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:128:in `manage_instance'                                                                                                                                                         
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman-google/app/lib/foreman_google/google_compute_adapter.rb:52:in `delete_instance'                                                                                                                                                          
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman-google/app/models/foreman_google/gce.rb:87:in `destroy_vm'                                                                                                                                                                               
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration/compute.rb:222:in `delCompute'                                                                                                                                                                         
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:227:in `execute'                                                                                                                                                                                    
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:152:in `block in process'                                                                                                                                                                           
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:144:in `each'                                                                                                                                                                                       
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:144:in `process'                                                                                                                                                                                    
 f7cb7548 | /home/aruzicka/vcs/foreman/foreman/app/models/concerns/orchestration.rb:60:in `on_destroy
```

**Review by adamruzicka — CHANGES_REQUESTED** [review]
Happy path seems to mostly work. The only catch is that the warning when removing a host warns that "This [the removal] will delete the linked VMs and their disks, and is irreversible.", however if I had an instance with an additional disk, that extra disk was left alone.

**Comment by stejskalleos** [comment]
Both issues fixed and added tests

**Review by adamruzicka — APPROVED** [review]
Works well

**Comment by adamruzicka** [comment]
Thank you @stejskalleos !

**Pull request merged**
